/*
 * Problem library browser: course > chapter > section > problem.
 *
 * The table of contents (js/library-data.js) is generated by
 * scripts/build_library_index.py; problems are embedded live from
 * Doenet.org. Where you are is kept in the URL
 * (?course=Algebra&section=8.3&problem=<id>), so locations can be
 * bookmarked or shared and the Back button works.
 */

const $ = (id) => document.getElementById(id);
const courses = LIBRARY.courses;
let state = {};
let renderedCourse = null;
let openedFrom = null; // problem card to return focus to on close

function readState() {
    const p = params();
    const course = courses.find((c) => c.id === p.get("course")) || courses[0];
    const sections = course.chapters.flatMap((chapter) =>
        chapter.sections.map((section) => ({ ...section, chapter })),
    );
    const section = sections.find((s) => s.key === p.get("section")) || null;
    const problem = section?.problems.find((pr) => pr.id === p.get("problem")) || null;
    return { course, section, problem };
}

function stateUrl({ course, section, problem }) {
    const p = new URLSearchParams({ course: course.id });
    if (section) p.set("section", section.key);
    if (problem) p.set("problem", problem.id);
    return `library.html?${p}`;
}

function navigate(next) {
    history.pushState(null, "", stateUrl(next));
    render();
}

window.addEventListener("popstate", render);

/** Plain-left-click on an in-app link navigates without a page load. */
function appLink(href, next, ...children) {
    return h(
        "a",
        {
            href,
            onclick: (event) => {
                if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey) return;
                event.preventDefault();
                navigate(next);
            },
        },
        ...children,
    );
}

function problemLabel(problem) {
    return problem.number ? `${problem.number} ${problem.title}` : problem.title;
}

function sectionLabel(section) {
    return section.number ? `${section.number} ${section.title}` : section.title;
}

// Course picker

$("course").append(...courses.map((c) => h("option", { value: c.id }, c.title)));
$("course").addEventListener("change", (event) => {
    navigate({ course: courses.find((c) => c.id === event.target.value) });
});

// Rendering

function render() {
    state = readState();
    $("course").value = state.course.id;
    if (renderedCourse !== state.course) {
        renderTree();
        renderedCourse = state.course;
    }
    updateTreeSelection();
    renderSection();
    renderPreview();
    document.title = [
        state.problem && problemLabel(state.problem),
        state.section && sectionLabel(state.section),
        `${state.course.title} Library`,
    ]
        .filter(Boolean)
        .join(" · ");
}

function renderTree() {
    const course = state.course;
    $("tree").replaceChildren(
        ...course.chapters.map((chapter) => {
            const count = chapter.sections.reduce((n, s) => n + s.problems.length, 0);
            return h(
                "details",
                { class: "chapter", "data-chapter": chapter.number },
                h(
                    "summary",
                    {},
                    h("span", { class: "chapter-name" }, `Ch. ${chapter.number} ${chapter.title}`),
                    h("span", { class: "count", "aria-label": `${count} problems` }, String(count)),
                ),
                h(
                    "ul",
                    {},
                    chapter.sections.map((section) =>
                        h(
                            "li",
                            {},
                            appLink(
                                stateUrl({ course, section }),
                                { course, section },
                                h("span", {}, sectionLabel(section)),
                                h("span", { class: "count", "aria-label": `${section.problems.length} problems` }, String(section.problems.length)),
                            ),
                        ),
                    ),
                ),
            );
        }),
    );
}

function updateTreeSelection() {
    const href = state.section ? stateUrl({ course: state.course, section: state.section }) : null;
    for (const link of $("tree").querySelectorAll("a")) {
        const current = link.getAttribute("href") === href;
        link.toggleAttribute("aria-current", current);
        if (current) link.closest("details").open = true;
    }
}

function renderSection() {
    const view = $("section-view");
    const { course, section } = state;

    if (!section) {
        const total = course.chapters.reduce(
            (n, ch) => n + ch.sections.reduce((m, s) => m + s.problems.length, 0),
            0,
        );
        view.replaceChildren(
            h("p", { class: "eyebrow" }, course.title),
            h("h2", {}, "Choose a chapter and section"),
            h(
                "p",
                { class: "muted" },
                `${course.chapters.length} chapters and ${total} problems. Open a chapter on the left to see its sections.`,
            ),
        );
        return;
    }

    // Re-rendering the same section only needs the selection updated, so the
    // list keeps its scroll position while previewing problems.
    if (view.dataset.section === `${course.id}/${section.key}`) {
        markSelectedProblem();
        return;
    }
    view.dataset.section = `${course.id}/${section.key}`;

    view.replaceChildren(
        h("p", { class: "eyebrow" }, `${course.title} · Ch. ${section.chapter.number} ${section.chapter.title}`),
        h("h2", { id: "section-title", tabindex: "-1" }, sectionLabel(section)),
        h("p", { class: "muted" }, `${section.problems.length} problem${section.problems.length === 1 ? "" : "s"}`),
        h(
            "ol",
            { class: "problem-list" },
            section.problems.map((problem) =>
                h(
                    "li",
                    {},
                    appLink(
                        stateUrl({ course, section, problem }),
                        { course, section, problem },
                        h("span", { class: "problem-number" }, problem.number || ""),
                        h("span", { class: "problem-title" }, problem.title),
                        problem.about ? h("span", { class: "problem-about" }, problem.about) : null,
                        problem.numVariants > 1
                            ? h("span", { class: "problem-meta" }, `${problem.numVariants} variants`)
                            : null,
                    ),
                ),
            ),
        ),
    );
    markSelectedProblem();

    if (window.matchMedia("(max-width: 799px)").matches) {
        view.scrollIntoView({ behavior: "smooth", block: "start" });
    }
}

function markSelectedProblem() {
    for (const link of $("section-view").querySelectorAll(".problem-list a")) {
        const current = state.problem && link.getAttribute("href") === stateUrl(state);
        link.toggleAttribute("aria-current", Boolean(current));
    }
}

// Preview panel

let previewedId = null;

function renderPreview() {
    const { course, section, problem } = state;
    const panel = $("preview");
    document.body.classList.toggle("preview-open", Boolean(problem));

    if (!problem) {
        if (!panel.hidden) {
            panel.hidden = true;
            $("preview-body").replaceChildren();
            previewedId = null;
            openedFrom?.focus();
        }
        return;
    }

    panel.hidden = false;
    if (previewedId === problem.id) return;
    previewedId = problem.id;

    $("preview-path").textContent = `${course.title} › Ch. ${section.chapter.number} › ${sectionLabel(section)}`;
    $("preview-title").textContent = problemLabel(problem);
    $("preview-doenet").href = `${DOENET_ORIGIN}/activityViewer/${encodeURIComponent(problem.id)}`;
    $("preview-copy-status").textContent = "";

    const index = section.problems.indexOf(problem);
    $("preview-prev").disabled = index === 0;
    $("preview-next").disabled = index === section.problems.length - 1;

    $("preview-refresh").hidden = !(problem.numVariants > 1);
    $("preview-body").replaceChildren(
        problem.about ? h("p", { class: "preview-about" }, problem.about) : "",
        h("div", { id: "preview-embed" }),
    );
    loadPreviewEmbed();

    $("preview-title").focus();
}

/** Each load of an embed picks a random variant, so reloading gives new numbers. */
function loadPreviewEmbed() {
    const { problem } = state;
    $("preview-embed").replaceChildren(createEmbed(problem, { title: problemLabel(problem) }).wrap);
}

function step(delta) {
    const { course, section, problem } = state;
    const next = section.problems[section.problems.indexOf(problem) + delta];
    if (next) navigate({ course, section, problem: next });
}

$("preview-prev").addEventListener("click", () => step(-1));
$("preview-next").addEventListener("click", () => step(1));
$("preview-close").addEventListener("click", closePreview);
$("preview-refresh").addEventListener("click", loadPreviewEmbed);
document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && state.problem) closePreview();
});

function closePreview() {
    navigate({ course: state.course, section: state.section });
}

// Remember which card opened the preview so focus can return there.
$("section-view").addEventListener("click", (event) => {
    const link = event.target.closest(".problem-list a");
    if (link) openedFrom = link;
});

$("preview-copy").addEventListener("click", async () => {
    const code = `<iframe src="${DOENET_ORIGIN}/embed/${state.problem.id}" width="100%" height="800" style="border: 0"></iframe>`;
    try {
        await navigator.clipboard.writeText(code);
        $("preview-copy-status").textContent = "Copied.";
    } catch {
        $("preview-copy-status").textContent = code;
    }
});

render();
